# Site settings
baseurl = "http://harry.ahlas.com"   #"http://harry.ahlas.com"  "/" "http://www.earlydemise.com/blogtest/"
#baseurl = "/" 
languageCode = "en-us"
title = "Harry Ahlas"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	name = "Harry Ahlas"
	description = "People analytics, data science, music, and audio engineering. Views are my own."
	bio = "Senior Data Science Advisor"
	# Enter optionally your twitter account
	twitter = "harry_ahlas"
	enableRSS = false#true

#added 1/21
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "python"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "People Analytics Manager"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/harry_ahlas"
    #facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/harryahlas"
    #dribble  = "https://www.dribbble.com/"
